# Development override - use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
version: '3.8'

services:
  api_app:
    build:
      context: .
      dockerfile: Dockerfile.api.dev
    depends_on:
      vn_test_db:
        condition: service_healthy
    volumes:
      # Mount source code for hot reload
      - .:/app
      - maven_cache:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - JAVA_OPTS=-Xmx512m -Xms256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      # TODO - add CI/CD variables here
      - SPRING_DATASOURCE_URL=jdbc:postgresql://vn_test_db:5432/vn_test?sslmode=disable
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=example
    ports:
      - "8081:8081"
      - "5005:5005"  # Debug port
    command: mvn spring-boot:run

  vn_test_db:
    build:
      context: ./database
      dockerfile: Dockerfile.postgres
    image: auto-postgres
    healthcheck:
    # TODO change postgres user to ci/cd variable...
    # Same with postgres_db
      test: ["CMD-SHELL", "pg_isready -U postgres -d vn_test"]
      interval: 15s,
      retries: 10
      timeout: 10s,
      start_period: 40s
      # start_interval: 5s
    restart: always
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init/:/docker-entrypoint-initdb.d/
      - ./database/db/:/db/
    environment:
      # TODO replace if we're running in prod
      POSTGRES_PASSWORD: example
      POSTGRES_DB: vn_test
    ports:
      - 5432:5432

  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pontusgrandin@proton.me
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - 8080:80  

volumes:
  maven_cache:
  postgres_data: